import Head from 'next/head'
import { Raleway } from 'next/font/google'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Team from '@/components/Team'
import Contact from '@/components/Contact'
import Services from '@/components/Services'
import { Element } from 'react-scroll'

const raleway = Raleway({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-[#f3f2f0] text-black'>
      <Head>
        <title>My Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />

        <Element name='hero'>
          <Hero />
        </Element>
        <Element name='about'>
          <About />
        </Element>
        <Element name='services'>
          <Services />
        </Element>
        <Element name='team'>
          <Team />
        </Element>
        <Element name='contact'>
          <Contact />
        </Element>
      </main>
    </div>
  )
}
